api:
  httpport: 8081
  logging: true
  loglevel: 4
  gziplevel: -1
store:
  host: "foa-db"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
factom:
  url: "https://api.factomd.net"
  user: ""
  password: ""
  esaddress: ""